CREATE DATABASE InLock_Games_Tarde;

USE InLock_Games_Tarde;

CREATE TABLE Estudios (
	EstudioId INT IDENTITY PRIMARY KEY,
	NomeEstudio VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Jogos (
	JogoId INT IDENTITY PRIMARY KEY,
	NomeJogo VARCHAR(255) UNIQUE NOT NULL,
	Descricao TEXT NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor DECIMAL NOT NULL,
	EstudioId INT FOREIGN KEY REFERENCES Estudios(EstudioId)
);

CREATE TABLE Usuarios (
	UsuarioId INT IDENTITY PRIMARY KEY,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(100) NOT NULL,
	TipoUsuario VARCHAR(255) NOT NULL UNIQUE
);